### ISSUE TITLE
max_records setting seems to be broken

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/vip-report#94]
When running with `--max_records 5` I get a report with all records in my VCF (27 in my example)

**Comment by dennishendriksen** [comment]
Nowadays we just dump all VCF bytes in the report output: https://github.com/molgenis/vip-report/blob/v5.5.2/src/main/java/org/molgenis/vcf/report/generator/ReportGenerator.java#L156. I propose to remove `max_records` and `max_samples` from the CLI.
